---
title: "Results"
author: "Chuyin"
date: "2021/7/31"
output: html_document
---

```{r setup, include=FALSE}
library("scales")
library(dplyr)
library(tidyverse)
library(ggplot2)
library('lme4')
#library('sjstats')
library(lmtest)
load('preprocessed.RData')

artificial = c(9999001, 9999002, 9999003, 9999004, 9999005, 9999006, 9999007, 9999008)
```


```{r sequence effect}
all_response$order[seq(5,63000,5)] = 5
temp = seq(1,63000,5)
all_response$order[temp] = 1
temp = seq(2,63000,5)
all_response$order[temp] = 2
temp = seq(3,63000,5)
all_response$order[temp] = 3
temp = seq(4,63000,5)
all_response$order[temp] = 4
```


```{r frequency - word IA}
frequency$wf = as.factor(frequency$wf)

#plot
frequency %>% filter(wf != 1) %>% ggplot(mapping = aes(x = wf, y = IA)) + 
  theme_bw() +
  geom_boxplot() +
  labs(
    y = "Word IA",
    x = "Report frequency"
  ) +
  theme(axis.title.x = element_text(size = 15, family = 'Times'), axis.title.y = element_text(size = 15, family = 'Times'))

frequency$wf = as.numeric(frequency$wf)
frequency %>% filter(wf != 1) %>% ggplot(mapping = aes(x = wf)) +
  theme_bw() +
  geom_histogram(bins = 29) +
  scale_x_continuous(breaks = seq(2, 30, 1)) +
  theme(axis.title.y = element_text(size = 15))

frequency %>% filter(wf != 1) %>% ggplot(mapping = aes(x = IA)) +
  theme_bw() +
  geom_histogram() +
  scale_x_continuous(breaks = seq(1, 0.25, -0.25)) +
  scale_x_reverse() +
  labs(y = 'Count') +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))
  
```


```{r}
top_ia
bottom_ia
```


```{r distributions of image-level variables}
#image IA
img_ia %>% ggplot(mapping = aes(x = imgIA)) + 
  theme_bw() +
  geom_density() +
  labs(x = 'Image IA') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

#1-person rate
img_ia %>% ggplot(mapping = aes(x = proportion)) +
  theme_bw() +
  geom_density() +
  labs(x = '1-Person rate', size = 5) +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

#freq
img_ia %>% ggplot(mapping = aes(x = frequency)) +
  theme_bw() +
  labs(x = 'Mean Frequency of words for each image') +
  geom_density(aes(y = ..density..)) +
  scale_x_continuous(breaks=seq(2, 10, 1)) +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))

#conf
img_ia %>% ggplot(mapping = aes(x = conf)) +
  theme_bw() +
  labs(x = 'Mean confidence rating of words for each image') +
  geom_density(aes(y = ..density..)) +
  scale_x_continuous(breaks=seq(1, 5, 1)) +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))
```


```{r distribution of confidence}
all_after %>% ggplot(mapping = aes(x = conf)) +
  theme_bw() +
  labs(x = 'Mean confidence for each word', y = 'Count') +
  geom_histogram() +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_after %>% ggplot(mapping = aes(x = IA)) +
  theme_bw() +
  labs(x = 'Word IA', y = 'Count') +
  geom_histogram() +
  scale_x_reverse() +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_after %>% ggplot(mapping = aes(x = conf, y = IA)) +
  theme_bw() +
  labs(y = 'Word IA', x = 'Mean confidence for each word') +
  geom_jitter() +
  geom_smooth(method = 'lm', color = 'yellow') +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))

#all_after = all_after %>% filter(!img_id %in% artificial)
cor.test(all_after$IA, all_after$conf)
```


```{r correlations}
#freq
img_ia %>% ggplot(mapping = aes(x = imgIA, y = frequency)) +
  theme_bw() +
  labs(x = 'Image IA', y = 'Mean frequency of words') +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))

#conf
img_ia %>% ggplot(mapping = aes(x = imgIA, y = conf)) +
  theme_bw() +
  labs(x = 'Image IA', y = 'Mean confidence rating') +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))

#1-person rate
img_ia %>% ggplot(mapping = aes(x = imgIA, y = proportion)) +
  theme_bw() +
  labs(x = 'Image IA', y = '1-person rate') +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

#img_ia = img_ia %>% filter(!img_id %in% artificial)
#correlation tests
cor.test(img_ia$imgIA, img_ia$frequency)
cor.test(img_ia$imgIA, img_ia$proportion)
cor.test(img_ia$imgIA, img_ia$conf)
cor.test(img_ia$proportion, img_ia$conf)
cor.test(img_ia$proportion, img_ia$frequency)
cor.test(img_ia$frequency, img_ia$conf)

cor.test(all_after$IA, all_after$freq)
cor.test(all_after$IA, all_after$conf)
```


#start# analysis of highly similar images
```{r SSE}
all_after = all_after %>% ungroup()
load('duplicate_similar_images.RData') #IDs of duplicate images
dup_results = data.frame(row.names = c('Image_1', 'Image_2', 'SSE'))
for (i in 2:nrow(duplicate_img_ids))
{
  temp = duplicate_img_ids[i,]
  temp1 = temp[1,2]
  temp = unlist(temp1)
  dup = all_after %>% filter(img_id == temp[1] | img_id == temp[2])
  words = data.frame(stem_word = unique(dup$stem_word))
  
  dup1 = all_after %>% filter(img_id == temp[1]) %>% select(-img_id)
  dup2 = all_after %>% filter(img_id == temp[2]) %>% select(-img_id)
  colnames(dup1)[2:4] = c('IA_1', 'freq_1', 'conf_1')
  colnames(dup2)[2:4] = c('IA_2', 'freq_2', 'conf_2')
  words = left_join(words, dup1, by = 'stem_word')
  words = left_join(words, dup2, by = 'stem_word')
  words[is.na(words)] = 0
  words = words %>% mutate(SE = (freq_1 - freq_2)^2/2)
  
  SSE = sum(words$SE)
  tmp = c(temp[1], temp[2], SSE)
  dup_results = rbind(dup_results, tmp)

}

colnames(dup_results) = c('Image_1', 'Image_2', 'SSE')

#an example
words %>% ggplot(mapping = aes(x = freq_1, y = freq_2)) +
  theme_bw() +
  geom_point(size = 3) +
  geom_abline(slope = 1, intercept = 0) +
  labs(x = 'Image 1', y = 'Image 2') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20)) +
  scale_x_continuous(breaks = seq(0, 12, 2))

```


```{r bootstrap}
bootstrap = data.frame(row.names = c('No.', 'mean_SSE'))
for (i in 1:100)
{
  dup_temp = data.frame(row.names = c('Image_1', 'Image_2', 'SSE'))
  for (j in 2:25)
  {
    temp1 = duplicate_img_ids[j,]
    temp = temp1[1,2]
    temp1 = unlist(temp)
    a = round(runif(1, 1, 2))
    
    b = round(runif(1, 2, 25))
    temp2 = duplicate_img_ids[b,]
    temp = temp2[1,2]
    temp2 = unlist(temp)
    c = round(runif(1, 1, 2))
    
    dup = all_after %>% filter(img_id == temp1[a] | img_id == temp2[c])
    words = data.frame(stem_word = unique(dup$stem_word))
  
    dup1 = all_after %>% filter(img_id == temp1[a]) %>% select(-img_id)
    dup2 = all_after %>% filter(img_id == temp2[c]) %>% select(-img_id)
    colnames(dup1)[2:4] = c('IA_1', 'freq_1', 'conf_1')
    colnames(dup2)[2:4] = c('IA_2', 'freq_2', 'conf_2')
    words = left_join(words, dup1, by = 'stem_word')
    words = left_join(words, dup2, by = 'stem_word')
    words[is.na(words)] = 0
    words = words %>% mutate(SE = (freq_1 - freq_2)^2/2)
  
    SSE = sum(words$SE)
    tmp = c(temp1[a], temp2[c], SSE)
    dup_temp = rbind(dup_temp, tmp)
  }
  colnames(dup_temp) = c('Image_1', 'Image_2', 'SSE')
  mean = mean(dup_temp$SSE)
  bootstrap = rbind(bootstrap, c(i, mean))
}
colnames(bootstrap) = c('Image_1', 'SSE')
```


```{r plot with 99%CI}
bootstrap = bootstrap %>% mutate(Image_2 = Image_1, type = 'random') %>% select(Image_1, Image_2, SSE, type)
dup_results$type = 'natural'
dup_results$type[25:28] = 'artificial'
dup_results = rbind(dup_results, bootstrap)

library(Rmisc)
naturalci = CI(dup_results$SSE[dup_results$type == 'natural'], ci = 0.99)
artificialci = CI(dup_results$SSE[dup_results$type == 'artificial'], ci = 0.99)
randomci = CI(dup_results$SSE[dup_results$type == 'random'], ci = 0.99)

dup_results %>% ggplot(mapping = aes(x = SSE, color = type)) +
  theme_bw() +
  geom_density(size = 1) +
  labs(x = 'Sum of Square of Error') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20)) +
  geom_errorbarh(aes(xmin = naturalci[1], xmax = naturalci[3], y = 0.005), height = 0.001, color = 'green', size = 1) +
  geom_errorbarh(aes(xmin = artificialci[1], xmax = artificialci[3], y = 0.0065), height = 0.001, color = 'red', size = 1) +
  geom_errorbarh(aes(xmin = randomci[1], xmax = randomci[3], y = 0.013), height = 0.001, color = 'blue', size = 1)

```
#end# analysis of highly similar images


#start# comparisons between SOA
```{r mean number of response words with conf > 1}
#detach("package:Rmisc", unload = TRUE)
#detach("package:plyr", unload = TRUE)
library('dplyr')
remove_conf1 = master_df %>% filter(confidence != 1)
participants = remove_conf1 %>% group_by(subject, img_id) %>% summarise(n = n(), soa = unique(soa))
number_soa = participants %>% group_by(soa) %>% summarise(mean = mean(n), sd = sd(n))

number_soa %>% ggplot(mapping = aes(x = soa, y = mean, color = soa, fill = soa)) +
  theme_bw() +
  geom_col(show.legend = FALSE) +
  labs(x = 'SOA', y = 'Mean number of words') +
  coord_cartesian(ylim = c(4,5)) +
  scale_y_continuous(breaks=seq(4, 5, 0.2)) +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20))

number_soa_image = participants %>% group_by(soa, img_id) %>% summarise(mean = mean(n), sd = sd(n))

number_soa_image %>% ggplot(mapping = aes(x = mean, color = soa, fill = soa)) +
  theme_bw() +
  geom_histogram() +
  labs(x = 'Mean number of words') +
  facet_wrap(~soa) +
  scale_x_continuous(breaks=seq(3, 5, 1)) +
  theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20))
```


#calculated and using word IA for each SOA
```{r remove conf = 1}
load(file = "IA_perSOA.RData")
IA_perSOA_after = IA_perSOA %>% filter(word_count != 1)

temp_IA = IA_perSOA_after %>% dplyr::select(-5,-6)
all_response = left_join(all_response, temp_IA, by = c('img_id','soa','stem_word'))
all_response = all_response %>% filter(!is.na(avg_type1auc))
```


```{r additional selection}
#some participants gave repetitive responses under the same image
temp = all_response %>% filter(avg_type1auc <= 0.5)
all_response = all_response %>% filter(avg_type1auc > 0.5)

#also remove from all_after
temp = temp %>% group_by(img_id, soa, stem_word) %>% summarise(n = n(), .groups = 'drop')
temp = temp %>% group_by(img_id, stem_word) %>% summarise(n = n(), .groups = 'drop')
temp = temp %>% filter(n == 1)
all_after = left_join(all_after, temp, by = c('img_id', 'stem_word'))
all_after = all_after %>% filter(is.na(n) | IA > 0.5) %>% select(-n)
```


```{r ANOVA}
library(car)
library(lsr)
img_ia_perSOA = IA_perSOA_after %>% group_by(img_id, soa) %>% summarise(imgIA = mean(avg_type1auc), freq = mean(word_count), conf = sum(word_count * mean_confidence)/sum(word_count), .groups = 'drop')
#img_ia_perSOA = img_ia_perSOA %>% filter(!img_id %in% artificial)

#freq
freqmodel = aov(freq ~ soa, data = img_ia_perSOA)
summary(freqmodel)
posthocPairwiseT(x = freqmodel, p.adjust.method = 'holm')
img_ia_perSOA %>% group_by(soa) %>% summarise(mean = mean(freq), sd = sd(freq)) %>% ungroup
freqresidual = freqmodel$residuals
#shapiro.test(x=freqresidual)
leveneTest(freq ~ soa, data = img_ia_perSOA)
oneway.test(freq ~ soa, data = img_ia_perSOA)

#conf
confmodel = aov(conf ~ soa, data = img_ia_perSOA)
summary(confmodel)
posthocPairwiseT(x = confmodel, p.adjust.method = 'holm')
img_ia_perSOA %>% group_by(soa) %>% summarise(mean = mean(conf), sd = sd(conf)) %>% ungroup
confresidual = confmodel$residuals
#shapiro.test(x=confresidual)
leveneTest(conf ~ soa, data = img_ia_perSOA)
oneway.test(conf ~ soa, data = img_ia_perSOA)

#image IA
IAmodel = aov(imgIA ~ soa, data = img_ia_perSOA)
summary(IAmodel)
posthocPairwiseT(x = IAmodel, p.adjust.method = 'holm')
img_ia_perSOA %>% group_by(soa) %>% summarise(mean = mean(imgIA), sd = sd(imgIA)) %>% ungroup
IAresidual = IAmodel$residuals
#shapiro.test(x=freqresidual)
leveneTest(imgIA ~ soa, data = img_ia_perSOA)
oneway.test(imgIA ~ soa, data = img_ia_perSOA)
```


```{r slope analysis}
#calculate the slopes
library(purrr)
IA_perSOA_after$soa = as.numeric(IA_perSOA_after$soa)
reg = IA_perSOA_after %>% group_by(img_id, soa) %>% summarise(IA = mean(avg_type1auc), freq = mean(word_count), conf = sum(word_count * mean_confidence)/sum(word_count))
reg = reg %>% group_nest(img_id)
reg = reg %>% mutate(model.ia = map(data, ~lm(IA ~ soa, data = .x)), model.conf = map(data, ~lm(conf ~ soa, data = .x)), model.freq = map(data, ~lm(freq ~ soa, data = .x)))

#get the slopes
result = reg %>% select(img_id)
temp = img_ia %>% select(img_id, imgIA)
result = left_join(result, temp, by = 'img_id')
temp = t(reg$model.ia %>% map_dfc('coefficients'))
result$slope.ia = temp[,2]
temp = t(reg$model.freq %>% map_dfc('coefficients'))
result$slope.freq = temp[,2]
temp = t(reg$model.conf %>% map_dfc('coefficients'))
result$slope.conf = temp[,2]

#plot
result %>% ggplot(mapping = aes(x = imgIA, y = slope.ia)) +
  theme_bw() +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  labs(x = 'Image IA', y = 'Slope') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

result %>% ggplot(mapping = aes(x = slope.ia)) +
  theme_bw() +
  geom_density() +
  labs(x = 'Slope') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

#result = result %>% filter(!img_id %in% artificial)
cor.test(result$imgIA, result$slope.ia)
```


```{r multi-level regression}
all_response$soa = as.character(all_response$soa)
all_response$soa = as.numeric(all_response$soa)
#all_response = all_response %>% filter(!img_id %in% artificial)

model1 = lmer("avg_type1auc ~ 1 + (1|subject) + (1|img_id)", data = all_response, control = lmerControl(optimizer="bobyqa"), REML = FALSE)
summary(model1)
performance::icc(model1)

model2 = lmer("avg_type1auc ~ 1 + confidence + (1|subject) + (1|img_id)", data = all_response, control = lmerControl(optimizer="bobyqa"), REML = FALSE)
summary(model2)
performance::icc(model2)
  
model3 = lmer("avg_type1auc ~ 1 + soa + confidence + (1|subject) + (1|img_id)", data = all_response, control = lmerControl(optimizer="bobyqa"), REML = FALSE)
summary(model3)
performance::icc(model3)

model4 = lmer("avg_type1auc ~ 1 + soa + confidence + soa * confidence + (1|subject) + (1|img_id)", data = all_response, control = lmerControl(optimizer="bobyqa"), REML = FALSE)
summary(model4)
performance::icc(model4)

anova(model1, model2)
lrtest(model1, model2)
anova(model2, model3)
lrtest(model2, model3)
anova(model3, model4)
lrtest(model3, model4)
AIC(model1, model2, model3, model4)
BIC(model1, model2, model3, model4)

SOA67 = all_response %>% filter(soa == 67)
cor.test(SOA67$confidence, SOA67$avg_type1auc)
SOA133 = all_response %>% filter(soa == 133)
cor.test(SOA133$confidence, SOA133$avg_type1auc)
SOA267 = all_response %>% filter(soa == 267)
cor.test(SOA267$confidence, SOA267$avg_type1auc)
```


```{r AICBIC}
temp1 = AIC(model1, model2, model3, model4)
colnames(temp1) = c('df', 'value')
temp1$model = c('Model 1', 'Model 2', 'Model 3', 'Model 4')
temp1$Method = 'AIC'
temp2 = BIC(model1, model2, model3, model4)
colnames(temp2) = c('df', 'value')
temp2$model = c('Model 1', 'Model 2', 'Model 3', 'Model 4')
temp2$Method = 'BIC'
selection = rbind(temp1, temp2)
selection %>% ggplot(mapping = aes(x = model, y = value, fill = Method)) +
  theme_bw() +
  geom_col(position = 'dodge') + 
  coord_cartesian(ylim = c(-80000, -75000)) +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20))
```


```{r figure}
all_response$soa = as.factor(all_response$soa)
all_response$confidence = as.numeric(all_response$confidence)

all_response %>% filter(soa == 267) %>% ggplot(mapping = aes(x = confidence)) +
  theme_bw() +
  geom_histogram(position = 'dodge',bins = 13) +
  labs(x = 'Confidence') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_response %>% filter(soa == 267) %>% ggplot(mapping = aes(x = avg_type1auc)) +
  theme_bw() +
  geom_histogram() +
  labs(x = 'Word IA') +
  scale_x_reverse() +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_response %>% ggplot(mapping = aes(x = confidence, y = avg_type1auc, fill = soa, color = soa)) +
  theme_bw() +
  geom_jitter(alpha = 0.4) +
  geom_smooth(method = 'lm') +
  facet_wrap(~soa) +
  labs(x = 'Confidence', y = "Word IA") +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_response %>% filter(soa == 267) %>% ggplot(mapping = aes(x = confidence, y = avg_type1auc)) +
  theme_bw() +
  geom_jitter(alpha = 0.4) +
  geom_smooth(method = 'lm', color = 'blue', size = 2) +
  labs(x = 'Confidence', y = "Word IA") +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_response %>% ggplot(mapping = aes(x = as.factor(confidence), y = avg_type1auc, fill = soa)) +
  theme_bw() +
  geom_boxplot() +
  labs(x = 'Confidence', y = "Word IA") +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))
```

----------------------------------------------------------------------------------

#reply to reviewers' concerns
#sequence effect
```{r sequence effect}
# temp = all_df %>% dplyr::select(1,2,3,4)
# X_sequence = left_join(all_response, temp, by = c('img_id', 'soa', 'stem_word'))
# cor.test(X_sequence$order, X_sequence$confidence)
# cor.test(X_sequence$order, X_sequence$avg_type1auc)
all_response$confidence = as.numeric(all_response$confidence)
all_response$order = as.numeric(all_response$order)
all_response$soa = as.numeric(all_response$soa)
cor.test(all_response$order, all_response$confidence)
cor.test(all_response$order, all_response$avg_type1auc)

model = lm(avg_type1auc ~ order + soa + order:soa, data = all_response)
summary(model)

all_response$order = as.factor(all_response$order)
all_response$soa = as.factor(all_response$soa)
all_response %>% ggplot(mapping = aes(x = order, y = avg_type1auc, fill = soa)) +
  theme_bw() +
  geom_boxplot() +
  geom_smooth(method = 'lm') +
  labs(x = 'Report sequence', y = 'Word IA') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

all_response %>% ggplot(mapping = aes(x = order, y = confidence, fill = soa)) +
  theme_bw() +
  geom_boxplot() +
  geom_smooth(method = 'lm') +
  labs(x = 'Report sequence', y = 'Confidence') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))
```


```{r dont know}
dontknow = all_response %>% group_by(order, confidence) %>% summarise(n = n(), .groups = 'drop')
temp = dontknow %>% group_by(order) %>% summarise(sum = sum(n), .groups = 'drop')
dontknow = left_join(dontknow, temp, by = 'order')
dontknow = dontknow %>% mutate(percent = n/sum) %>% filter(confidence == 1)

dontknow %>% ggplot(mapping = aes(x = order, y = percent)) +
  theme_bw() +
  geom_col() +
  labs(x = 'Report sequence', y = '% of dont know') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))
```


```{r sperling}
sperling = all_response %>% filter(img_id == 9999001 | img_id == 9999002)
sperling = sperling %>% mutate(length = nchar(stem_word))
# specific = sperling %>% mutate(length = nchar(stem_word)) %>% filter(length == 1)
# generic = sperling %>% mutate(length = nchar(stem_word)) %>% filter(length != 1)
sperling$type[sperling$length == 1] = 'specific'
sperling$type[sperling$length > 1] = 'generic'
# specific_sum = length(specific$length)
# generic_sum = length(generic$length)

# specific = specific %>% group_by(order) %>% summarise(n = n(), .groups = 'drop') %>% mutate(percent = n/specific_sum)
# generic = generic %>% group_by(order) %>% summarise(n = n(), .groups = 'drop') %>% mutate(percent = n/generic_sum)
specific = length(sperling$type[sperling$type == 'specific'])
generic = length(sperling$type[sperling$type == 'generic'])

sperling_response = sperling %>% group_by(order, type) %>% summarise(n = n(), .groups = 'drop')
sperling_response_1 = sperling_response %>% filter(type == 'specific') %>% mutate(percent = n/specific)
sperling_response_2 = sperling_response %>% filter(type == 'generic') %>% mutate(percent = n/generic)
sperling_response = rbind(sperling_response_1, sperling_response_2)

sperling_response %>% ggplot(mapping = aes(x = order, y = percent, fill = type)) +
  theme_bw() +
  geom_col(position = 'dodge') +
  labs(x = 'Report sequence', y = '% of responses') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

table = table(sperling$type, sperling$order)
chisq.test(table)
# specific %>% ggplot(mapping = aes(x = order, y = percent)) +
#   theme_bw() +
#   geom_col() +
#   labs(x = 'Report sequence', y = '%', title = 'specific words') +
#   coord_cartesian(ylim = c(0,0.3)) +
#   theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))
# 
# generic %>% ggplot(mapping = aes(x = order, y = percent)) +
#   theme_bw() +
#   geom_col() +
#   labs(x = 'Report sequence', y = '%', title = 'generic words') +
#   coord_cartesian(ylim = c(0,0.3)) +
#   theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

sperling$order = as.numeric(sperling$order)
modelS = lmer("order ~ 1 + type + (1|subject)", data = sperling, control = lmerControl(optimizer="bobyqa"), REML = FALSE)
summary(modelS)
performance::icc(modelS)
```


#relationship between IA and SOA
```{r IA ~ SOA}
all_response$confidence = as.factor(all_response$confidence)

all_response %>% ggplot(mapping = aes(x = confidence, y = avg_type1auc, fill = soa)) +
  theme_bw() +
  geom_boxplot() +
  labs(x = 'Confidence', y = "Word IA") +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))
```


```{r without conf = 1}
all_response = all_response %>% filter(confidence != 1)
model = aov(avg_type1auc ~ soa, data = all_response)
summary(model)
posthocPairwiseT(x = model, p.adjust.method = 'holm')
IAresidual = model$residuals
#shapiro.test(x=IAresidual)
leveneTest(avg_type1auc ~ soa, data = all_response)
oneway.test(avg_type1auc ~ soa, data = all_response)
kruskal.test(avg_type1auc ~ soa, data = all_response)

```



#motivation of IA
```{r example AUC by confidence}
target = all_response %>% filter(img_id == 2277 & stem_word == 'eiffel-tower')
other = all_response %>% filter(img_id != 52277 & stem_word == 'eiffel-tower')

n_present = length(target$confidence)
n_absent = length(other$confidence)

roc = data.frame(criterion = numeric(1), hit = numeric(1), fa = numeric(1), stringsAsFactors = FALSE)
c_list = c(10, 5, 4, 3, 2, 1, 0)
for (i in c_list){
  temp_hit = target %>% filter(confidence >= i)
  hit = length(temp_hit$confidence)
  temp_fa = other %>% filter(confidence >= i)
  fa = length(temp_fa$confidence)
  if(n_absent == 0){fa_cum = 0} else{fa_cum = fa/(419*30)}
  hit_cum = hit/30
  if(i == 0){
    fa_cum = 1
    hit_cum = 1
    }  
  roc = rbind(roc, c(i, hit_cum, fa_cum))
}

roc = roc[-1,]
roc_df <- transform(roc, dFPR = c(diff(fa), 0), dTPR = c(diff(hit), 0))
auc=sum((roc_df$hit*roc_df$dFPR)) + sum(sum(roc_df$dTPR*roc_df$dFPR)/2)

print(auc)

roc_df %>% ggplot(mapping = aes(x = fa, y = hit)) +
  theme_bw() +
  geom_point(size=5) +
  geom_path(size=2) +
  geom_abline(intercept = 0, slope = 1, color="red", linetype="dashed", size=1.5)+
  scale_x_continuous(limits=c(0, 1)) +
  scale_y_continuous(limits=c(0, 1)) +
  ylab("Hit rate") +
  xlab("False alarm rate") +
  theme(axis.text=element_text(size=20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20)) +
  coord_fixed(ratio = 1) 

roc = roc[-1,]
roc %>% ggplot() +
  theme_bw() +
      geom_path(aes(x=criterion, y=hit), colour="green", size=2) +
      geom_point(aes(x=criterion, y=hit), colour="green", size=5) +
      geom_path(aes(x=criterion, y=fa), colour="red", size=2) +
      geom_point(aes(x=criterion, y=fa), colour="red", size=5) +
      scale_x_continuous(limits=c(1, 5)) +
      scale_y_continuous(limits=c(0, 1)) +
      scale_x_reverse() +
      #scale_x_reverse(labels = percent) + 
      xlab("Confidence") +
      ylab("Cumulative Percentage") +
      theme(axis.text=element_text(size=20), axis.title.x = element_text(size = 25), axis.title.y = element_text(size = 25)) +
      coord_fixed(ratio = 5) 
    
```


```{r confidence & ratio}
load(file = "Confidence_IA.RData")

cor.test(Confidence_IA$IA, Confidence_IA$auc)
cor.test(Confidence_IA$IA, Confidence_IA$ratio)

Confidence_IA %>% ggplot(mapping = aes(x = IA, y = auc)) +
  theme_bw() +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  scale_x_continuous(limits=c(0, 1)) +
  scale_y_continuous(limits=c(0, 1)) +
  coord_fixed(ratio = 1) +
  geom_abline(intercept = 0, slope = 1, color = 'red') +
  labs(x = 'Word IA', y = 'AUC by confidence') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

# Confidence_IA %>% ggplot(mapping = aes(x = IA, y = ratio)) +
#   theme_bw() +
#   geom_jitter() +
#   geom_smooth(method = 'lm') +
#   labs(x = 'Word IA', y = 'simple ratio of target/all') +
#   theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

Confidence_IA %>% ggplot(mapping = aes(x = ratio)) +
  theme_bw() +
  geom_histogram() +
  labs(x = 'Ratio1') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

Confidence_IA %>% ggplot(mapping = aes(x = auc, y = wf)) +
  theme_bw() +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  labs(x = 'AUC by confidence', y = 'Report frequency') +
  scale_x_continuous(limits=c(0.4, 1)) +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

Confidence_IA %>% ggplot(mapping = aes(x = auc)) +
  theme_bw() +
  geom_histogram() +
  labs(x = 'AUC by confidence') +
  scale_x_continuous(limits=c(0.4, 1)) +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

# Confidence_IA %>% filter(wf != 1) %>% ggplot(mapping = aes(x = IA, y = auc)) +
#   theme_bw() +
#   geom_jitter() +
#   geom_smooth(method = 'lm') +
#   labs(x = 'Word IA', y = 'AUC by confidence', title = 'Without rarely reported words') +
#   theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

```


#Sum IA
```{r sum IA}
ia_sum = all_after %>% group_by(img_id) %>% summarise(sumIA = sum(IA), imgIA = mean(IA), n = n(), .groups = 'drop')

cor.test(ia_sum$sumIA, ia_sum$imgIA)

ia_sum$n = as.factor(ia_sum$n)

ia_sum %>% ggplot(mapping = aes(x = imgIA, y = sumIA, color = n)) +
  theme_bw() +
  geom_point() +
  geom_smooth(method = 'lm') +
  labs(x = 'Image IA', y = 'Sum IA', color = '# of words') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20)) +
  theme(legend.key.size = unit(0.45,'cm'))
```


```{r sum IA}
ia_sum_soa = IA_perSOA_after %>% group_by(img_id, soa) %>% summarise(sumIA = sum(avg_type1auc), imgIA = mean(avg_type1auc), n = n(), conf = mean(mean_confidence), .groups = 'drop')

ia_sum_soa$soa = as.factor(ia_sum_soa$soa)

ia_sum_soa %>% ggplot(mapping = aes(x = soa, y = sumIA)) +
  theme_bw() +
  geom_boxplot() +
  labs(x = 'SOA', y = 'Sum IA per SOA', color = '# of words') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

ia_sum_soa %>% ggplot(mapping = aes(x = soa, y = imgIA)) +
  theme_bw() +
  geom_boxplot() +
  labs(x = 'SOA', y = 'Image IA per SOA', color = '# of words') +
  theme(axis.title.x = element_text(size = 30), axis.title.y = element_text(size = 30), axis.text = element_text(size = 20))

model1 = aov(imgIA ~ soa, data = ia_sum_soa)
summary(model1)
posthocPairwiseT(x = model1, p.adjust.method = 'holm')
residual1 = model1$residuals
shapiro.test(x=residual1)
leveneTest(imgIA ~ soa, data = ia_sum_soa)
oneway.test(imgIA ~ soa, data = ia_sum_soa)

model2 = aov(sumIA ~ soa, data = ia_sum_soa)
summary(model2)
posthocPairwiseT(x = model2, p.adjust.method = 'holm')
residual2 = model2$residuals
shapiro.test(x=residual2)
leveneTest(sumIA ~ soa, data = ia_sum_soa)
oneway.test(sumIA ~ soa, data = ia_sum_soa)
```


```{r display images}
source('function-image_utilities.R')
ia_sum = ia_sum %>% arrange(sumIA)
ia_sum$sumIA = round(ia_sum$sumIA, 2)
ia_sum$imgIA = round(ia_sum$imgIA, 2)
gimp <- ggplot(data.table(x=0:16, y=0:16), aes(x=x, y=y)) +
  scale_x_continuous(limits=c(0, 9.5)) +
  scale_y_continuous(limits=c(0, 16)) +
  #xlim(0, 3) + ylim(0, 54) +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks = element_blank(),axis.title.x=element_blank(),axis.title.y=element_blank(),
          panel.grid.major=element_blank(),panel.grid.minor=element_blank(),
        panel.background = element_blank())+
        coord_fixed(ratio = 1)
nishimoto_images_folder = './shinji-images/'
posx = 0
posy = 16
k = 0
for (i in ia_sum$img_id[1:84]) {
  print(i)
    gimp <- gimp + annotation_raster(image_scale(get_image_by_id(nishimoto_images_folder, i), "200"), ymin = posy, ymax=posy - 0.9, xmin=posx, xmax=posx + 1.6) +
      ggplot2::annotate("text", x=posx + 0.8, y = posy - 1, label=paste0(as.character(ia_sum$sumIA[ia_sum$img_id == i]), " (", as.character(ia_sum$imgIA[ia_sum$img_id == i]), ")"), size = 5)
    posx = posx + 1.61
    k = k + 1
    if(k == 6){
      posy = posy - 1.1
      posx = 0
      k = 0
    }
  }
  
  ggsave(gimp, height = 16, width = 10, filename = "2.png", limitsize = FALSE) 
```


--------------------------------------------------------

#no longer relevant
```{r}
roc = data.frame(hit = c(rep(0,18),rep(1,10)))
roc$fa = c(rep(0,18),rep(10/419,9),1)
roc_df <- transform(roc, dFPR = c(diff(fa), 0), dTPR = c(diff(hit), 0))
auc=sum((roc_df$hit*roc_df$dFPR)) + sum(sum(roc_df$dTPR*roc_df$dFPR)/2)
auc

all_words = all_after %>% group_by(stem_word) %>% summarise(word_ia = mean(IA), .groups = 'drop')
```


```{r}

```


```{r}

```


```{r}

```



```{r}
colnames(AI) = c('word','freq')
ai = c()
for (i in 1:31) {
  tempw = replicate(as.character(AI[i,1]), n = as.numeric(AI[i,2]))
  ai = c(ai, tempw)
}
df = as.data.frame(ai)
write.csv(df, file = 'ai.csv')
```


